create table board (
        dtype varchar(31) not null,
        board_id bigint not null generated by default as identity,
        board_content varchar(255),
        create_date timestamp,
        delete_date timestamp,
        last_modified_date timestamp,
        board_title varchar(255),
        board_views integer,
        region varchar(255),
        user_id bigint,
        primary key (board_id)
    );
--create table users (
--        user_id bigint not null generated by default as identity,
--        user_age integer,
--        create_date timestamp,
--        delete_date timestamp,
--        last_modified_date timestamp,
--        user_email_id varchar(255),
--        user_gender varchar(255),
--        user_name varchar(255),
--        user_nickname varchar(255),
--        user_password varchar(255),
--        primary key (user_id)
--    );
--
--create table comment (
--        comment_id bigint not null generated by default as identity,
--        comment_content varchar(255),
--        create_date timestamp,
--        delete_date timestamp,
--        last_modified_date timestamp,
--        board_id bigint,
--        parent_id bigint,
--        user_id bigint,
--        primary key (comment_id)
--    );
--
--create table like_board (
--        like_board_id bigint not null generated by default as identity,
--        board_id bigint,
--        user_id bigint,
--        primary key (like_board_id)
--    );
--
--create table upload_file (
--        upload_file_id bigint not null generated by default as identity,
--        store_file_name varchar(255),
--        upload_file_name varchar(255),
--        board_id bigint,
--        primary key (upload_file_id)
--    );
--
--
----alter table user
----       add constraint UK_9bdwue0w2vx6h12cgeet91i2q unique (user_email_id)
----
----    alter table user
----       add constraint UK_cr59axqya8utby3j37qi341rm unique (user_nickname)
----
----    alter table board
----       add constraint FKfyf1fchnby6hndhlfaidier1r
----       foreign key (user_id)
----       references user
----
----    alter table comment
----       add constraint FKlij9oor1nav89jeat35s6kbp1
----       foreign key (board_id)
----       references board
----
----    alter table comment
----       add constraint FKde3rfu96lep00br5ov0mdieyt
----       foreign key (parent_id)
----       references comment
----
----    alter table comment
----       add constraint FK8kcum44fvpupyw6f5baccx25c
----       foreign key (user_id)
----       references user
----
----    alter table like_board
----       add constraint FK5steqwy6ycb09bb386lgn6snh
----       foreign key (board_id)
----       references board
----
----    alter table like_board
----       add constraint FK8gbvrrl3dsh7irvcfn7af1j1y
----       foreign key (user_id)
----       references user
----
----    alter table upload_file
----       add constraint FK3gnkkwvdgucoijp01j1rp0xwy
----       foreign key (board_id)
----       references board